name: cypress

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'doc/**'
      - '**.md'
      - 'bin/**'
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'doc/**'
      - '**.md'
      - 'bin/**'

jobs:
  cypress:

    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:12.3
        env:
          POSTGRES_PASSWORD: password
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Install PostgreSQL client
        run: |
          sudo apt-get -yqq install libpq-dev

      - name: Build App
        env:
          POSTGRES_HOST: localhost
          DATABASE_HOST: localhost
          POSTGRES_USER: postgres
          CASA_DATABASE_PASSWORD: password
          POSTGRES_PASSWORD: password
          POSTGRES_HOST_AUTH_METHOD: trust
          POSTGRES_PORT: 5432
        run: |
          yarn
          bundle exec rake db:create
          bundle exec rake db:schema:load
          bundle exec rails webpacker:compile

      - name: Run cypress
        env:
          POSTGRES_HOST: localhost
          DATABASE_HOST: localhost
          POSTGRES_USER: postgres
          CASA_DATABASE_PASSWORD: password
          POSTGRES_PASSWORD: password
          POSTGRES_HOST_AUTH_METHOD: trust
          POSTGRES_PORT: 5432
          SKIP_BULLET: true
        run: |
          RAILS_ENV=test bundle exec rails server -b 0.0.0.0 -p 4040 -d
          RAILS_ENV=test bundle exec rake db:migrate
          RAILS_ENV=test bundle exec rake db:seed
          npm run test:cypress --exit-code 0

